[package]
name = "gearly-product"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
diesel = { version = "2.3.11", features = ["mysql", "chrono"] }
dotenv = "0.15.0"
tokio = {version = "1.52.3", features =["full"]}
reqwest = { version = "0.13.4", features = ["json"] }
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"]}
chrono = {version = "0.4.45", features = ["serde"]}
serde = "1.0.229"
deadpool-diesel = { version = "0.6.1", features = ["mysql"] }
anyhow = "1.0.104"
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0.151"
